# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mac2 <- function(X, Y, Z, nx, ny, k) {
    .Call(`_RBET_mac2`, X, Y, Z, nx, ny, k)
}

